import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import Link from 'next/link'

export default function Home() {

  const [data, setData] = useState();

  const apiKey = "ntiWUplo2K69bdOstoJeNMViBszdT8BoBK1oeChi"
  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`

  const getTechTransferData = async () => {
    const res = await axios.get(url);
    const info = await res.data;
    console.log(info);
    setData(info)
  }

  useEffect(() => {
    getTechTransferData();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>NASA POLYCHROMATIC</h1>
        <Link className={styles.Link} href="/polychromatic">click to see polychromatic views</Link>

  <div className={styles.gridContainer}>
    {data &&
      data.results.map((tech, index) => {
        return (
          <div key={index}>
            {tech &&
              tech.map((t, ind) => {
                if (ind === 10) {
                  return (
                    <div key={ind}>
                      <Image src={t} alt={t} width={100} height={100} />
                    </div>
                  );
                }
              })}
          </div>
        );
      })}
  </div>
</main>
</>
  )
 }